apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials-secret
            namespace: external-secrets
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-credentials-secret
            namespace: external-secrets
            key: AWS_SECRET_ACCESS_KEY
