apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vitess-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vitess-credentials
    template:
      engineVersion: v2
      data:
        users.json: |
          {
            "{{ .DB_USER }}": [{
              "UserData": "{{ .DB_USER }}",
              "Password": "{{ .DB_PASSWORD }}"
            }]
          }
  dataFrom:
    - extract:
        key: /dev/apocrypha/db
