apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vitess-dev

resources:
  - ../../base
  - credentials.yaml

patches:
  - path: cells.yaml
    target:
      kind: VitessCluster
      name: vitess-cluster
  - path: env.yaml
    target:
      kind: Deployment
      name: vitess-operator
