apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eck-secret-store
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
        url: "https://kubernetes.default.svc"
      auth:
        serviceAccount:
          name: external-secrets-sa
      remoteNamespace: eck-dev
