apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-server-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        DB_URL: "mysql://{{ .DB_USER }}:{{ .DB_PASSWORD }}@vitess-vtgate.vitess-dev.svc.cluster.local:3306/main"
  dataFrom:
    - extract:
        key: /dev/apocrypha/api
    - extract:
        key: /dev/apocrypha/db
