apiVersion: v1
kind: Service
metadata:
  name: wireguard
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.101
spec:
  type: LoadBalancer
  ports:
    - name: peer-0
      port: 51820
      protocol: UDP
      targetPort: 51820
    - name: peer-1
      port: 51821
      protocol: UDP
      targetPort: 51821
    - name: peer-2
      port: 51822
      protocol: UDP
      targetPort: 51822
  selector:
    name: wireguard
