apiVersion: v1
kind: Service
metadata:
  name: vitess-vtgate
  labels:
    app: vitess
    component: vtgate
spec:
  selector:
    planetscale.com/component: vtgate
    planetscale.com/cluster: vitess-cluster
  ports:
    - name: http
      port: 80
      targetPort: 15000
    - name: https
      port: 443
      targetPort: 15000
    - name: grpc
      port: 15999
      targetPort: 15999
    - name: mysql
      port: 3306
      targetPort: 3306
