---
- name: Create Namespace
  kubernetes.core.k8s:
    name: external-secrets
    api_version: v1
    kind: Namespace
    state: present

- name: Create AWS Credentials Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aws-credentials-secret
        namespace: external-secrets
      type: Opaque
      stringData:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

- name: Setup External Secrets Operator
  kubernetes.core.k8s:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: external-secrets
        namespace: argocd
      spec:
        project: default
        sources:
          - repoURL: "{{ GIT_REPO_URL }}"
            targetRevision: "{{ env }}"
            path: "roles/app/files/external_secrets"
          - repoURL: https://charts.external-secrets.io
            chart: external-secrets
            targetRevision: "{{ EXTERNAL_SECRET_VERSION }}"
            helm:
              valueFiles:
                - "values.yaml"
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: external-secrets
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
