affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/storage-node
              operator: DoesNotExist
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
